flex proba
KoraOrvatnew/study pull request #8
Opened 2024-12-19 19:46 UTC by KoraOrvatnew

2024-12-20 07:00 UTC, mhasilau requested changes

2024-12-20 07:00 UTC, mhasilau commented on dz6/flex.css
> +	width: 300px;
и здесь

2024-12-20 07:00 UTC, mhasilau commented on dz6/flex.css
> +	width: 300px;
и здесь

2024-12-23 20:18 UTC, KoraOrvatnew commented
fixed width and height: pixels to percentages

2024-12-23 23:33 UTC, KoraOrvatnew commented
add grid proba

2024-12-24 10:34 UTC, mhasilau approved these changes

2024-12-24 10:34 UTC, mhasilau commented on dz6/flex.css
> +	width: 600px;
здесь надо ширину сделать тоже в %. некрасиво смотриться, когда шапка и подвал на всю страницу, а внутри блоки узкие

2024-12-24 15:17 UTC, merged