Test1
KoraOrvatnew/study pull request #9
Opened 2024-12-24 18:20 UTC by KoraOrvatnew

2024-12-30 10:34 UTC, mhasilau requested changes

2024-12-30 10:34 UTC, mhasilau commented on test1/test1_v2.html
> +    <table border="1px">
верстка должна была быть не табличной

2024-12-30 10:34 UTC, mhasilau commented on test1/test1_v2.html
> +                  <button class="round2">
это просто информация. не должно быть кнопкой

2024-12-30 10:34 UTC, mhasilau commented on test1/test1_v2.html
> +                  <button class="round2">
зачем тут кнопки?

2024-12-30 10:34 UTC, mhasilau commented on test1/test1_v2.html
> +                    <br>
<br> лучше не использовать. если надо на разных строках - используй блочные теги

2024-12-30 10:34 UTC, mhasilau commented on test1/test1_v2.html
> +          <button class="round2">
зачем все оборачивать в кнопки? нажимать можно на все, что угодно

2024-12-30 10:34 UTC, mhasilau commented on test1/test1_v2.html
> +                <td>
нет выравнивания внутри блока (в данном случае ячейки)

2024-12-30 10:36 UTC, mhasilau commented on test1/test1_v2.html
> +                <td>
раз таблица - не надо было показывать границы ячеек

2024-12-30 10:37 UTC, mhasilau commented on test1/test1_v2.html
> +                <td>
коментарии касаются не только мест, шде они указаны, а ко всем похожим

2025-01-14 18:34 UTC, merged

2025-01-14 18:34 UTC, KoraOrvatnew commented
dorabotat